### ISSUE TITLE
docs image won't build in d4m 18.09.02

### ISSUE THREAD

**Issue by landism** [windmilleng/tilt.build#101]
When running `tilt up` at 50f0b74 with docker 18.09.02, I get:
```
    ╎ [5/9] ADD src/Gemfile* /src/
    ╎ [6/9] ADD docs/Gemfile* /docs/
    ╎   → panic: failed to copy /src-0/Gemfile* to docs/: lstat /src: no such file or directory
goroutine 1 [running]:
main.main()
    /go/src/github.com/tonistiigi/copy/cmd/copy/main.go:57 +0x2af
    ╎ ERROR IN: [6/9] ADD docs/Gemfile* /docs/
ERROR: ImageBuild: executor failed running [copy --unpack /src-0/Gemfile* docs/]: exit code: 2
```

This was introduced by b9f20d8a.
It repros if I change the dockerfile to
```
RUN mkdir /docs
ADD docs/Gemfile* /docs/
RUN mkdir -p /src
ADD src/Gemfile* /src/
```
(just to reduce the chance the `/src` in the error message is our `/src`

And doesn't repro if I replace
```
ADD docs/Gemfile*
```
with
```
ADD docs/Gemfile /docs/
ADD docs/Gemfile.lock /docs/
```
which, AIUI, should be exactly the same (given those are the only two files matching `docs/Gemfile*`

Also: `docs/Gemfile*` are symlinks to the same files in `src`. If I replace the symlinks with copies of their destinations, the problem goes away!

This all repros if I build outside of tilt w/ `DOCKER_BUILDKIT=1 docker build`.

**Comment by nicks** [comment]
verified that this is fixed at buidlkit HEAD, but it might take some time for the fix to make it out. closing this, as there's no further action to take
