### ISSUE TITLE
Add index/ToC for API ref

### ISSUE THREAD

**Issue by samscott89** [windmilleng/tilt.build#144]
It would be super helpful if there was a more compact list of the classes/methods on the API reference page, maybe at the top or in a side bar. This would help with (a) discoverability of new methods, and (b) navigation.

Thanks!

**Comment by jazzdan** [comment]
This looks [possible to do in sphinx](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html)!

**Comment by nicks** [comment]
https://docs.tilt.dev/api.html has a TOC at the top now

**Comment by samscott89** [comment]
Thanks! I've actually already used this a bunch recently without remembering I opened this issue. Super useful.
