### ISSUE TITLE
example_python  "Recommended Tiltfile" link is bad

### ISSUE THREAD

**Issue by bkcsfi** [windmilleng/tilt.build#505]
Hi,

On this page

https://github.com/windmilleng/tilt.build/blob/master/docs/example_python.md

The link "Recommended Tiltfile" on https://docs.tilt.dev/example_python.html  points to https://github.com/windmilleng/tilt-example-python/tree/master/2-recommended   but that link returns 404

**Comment by maiamcc** [comment]
Good catch, fixed! Thanks :)
